import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const navLinkClass =
  "font-bold text-md tracking-widest text-gray-700 px-4 py-3 rounded-lg transition-colors hover:text-gray-900 hover:bg-[linear-gradient(100deg,_#D2F3FC,_#FACFCE)]";

  const links = [
    { href: "/", label: "Home" },
    { href: "/news", label: "Publier" },
    { href: "/archives", label: "Archives" },
    { href: "/users", label: "Utilisateurs" },
  ];
  

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* HEADER */}
        <div className="min-h-screen flex flex-row">
        <header className="border-b p-4">
          <nav className="flex flex-col gap-4">
            <Link href="/" className="font-bold tracking-[0.25em] text-2xl uppercase py-2 mb-2">
              La CLEF
            </Link>

            {links.map(link => (
              <Link
                key={link.href}
                href={link.href}
                className={navLinkClass}
              >
                {link.label}
              </Link>
            ))}
          </nav>

        </header>

        <main className="p-6">
          {children}
        </main>
        </div>
      </body>
    </html>
  );
}
